### ISSUE TITLE
Кастомный формат кода

### ISSUE THREAD

**Issue by strangeman** [akeinhell/redfoxbot#69]
Хочется в настройках бота (в идеале в вебморде) задавать регулярку, по которой будут отлавливаться коды. `a-z0-9` не всегда достаточно, часто бывает нужна кириллица, или например все коды должны быть с префиксом.

**Comment by akeinhell** [comment]
@strangeman спасибо :-) сейчас ведется разработка новой версии, в которой учтем данное пожелание
