### ISSUE TITLE
При развертывании Лисы у себя на сервере (со своим telegram-ботом) отдается ссылка на "основной" бот Лисы

### ISSUE THREAD

**Issue by strangeman** [akeinhell/redfoxbot#70]
Надо добавить настройку `bot_login` в `.env`, чтобы кнопки 'Закинуть в личку' и 'Закинуть в чат' генерировали корректные ссылки на добавление телеграм-бота.

**Comment by akeinhell** [comment]
@strangeman спасибо :-) сейчас ведется разработка новой версии, в которой учтем данное пожелание
